# Generated by Django 5.0.3 on 2024-03-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mastertool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='atividade',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='aluno',
            field=models.ManyToManyField(blank=True, to='app_mastertool.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='periodo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
