# Generated by Django 5.0.3 on 2024-08-31 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mastertool', '0006_alter_atividade_alunos_alter_atividade_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='turma',
        ),
        migrations.AddField(
            model_name='notaatividade',
            name='turma',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='atividade_nota_turma', to='app_mastertool.turma'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='atividade',
            field=models.ManyToManyField(blank=True, to='app_mastertool.atividade'),
        ),
    ]
