# Generated by Django 5.0.3 on 2024-08-31 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mastertool', '0007_remove_atividade_turma_notaatividade_turma_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotaAtividade',
        ),
    ]
