# Generated by Django 5.0.3 on 2024-08-31 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mastertool', '0008_delete_notaatividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='atividade',
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
