# Generated by Django 5.0.3 on 2024-09-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mastertool', '0010_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='titulo',
            field=models.CharField(default='PROVA', max_length=100),
        ),
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
