# Generated by Django 5.0.3 on 2025-01-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mastertool', '0011_nota_titulo_alter_nota_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
