# Generated by Django 5.0.3 on 2025-01-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mastertool', '0012_nota_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
